In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
!pip install readability
import readability
!pip install syllables
import syllables
!pip install textstat
import textstat

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pickle
pickle_in = open('/content/drive/MyDrive/IIM Nagpur NLP Files/CellPhoneandAccessoriesNER.pickle', 'rb')
df = pickle.load(pickle_in)
df.head()

Rating  verified   reviewTime  Year      reviewerID        asin style  \
0       1     False  09 21, 2004  2004   A5JLAU2ARJ0BO  B0000E3GWH   NaN   
1       4     False  07 24, 2004  2004  A1ACM1CBGORBN1  B0000E3GWH   NaN   
2       3     False   07 6, 2004  2004  A2V48Q03FZUOSD  B0000E3GWH   NaN   
3       5      True  04 12, 2004  2004  A1V3TRGWOMA8LC  B0000E3GWH   NaN   
4       3     False  02 19, 2004  2004  A3NOBH42C7UI5M  B0000E3GWH   NaN   

     reviewerName                                         reviewText  \
0    Old-and-Wise  This phone is ugly and heavy and has a terribl...   
1    Sherry Berry  I had the Samsung V205 and then I decided to t...   
2  Benjamin David  This is the first Samsung phone I have had and...   
3   James Beswick  ..and I'm from Europe, where the phones and ne...   
4          Kepela  This phone is amazingly small and light for a ...   

                                           summary  vote  Image  no_of_sent  \
0                                    Bad reception     2      0           5   
1  Pretty good phone.. an improvement from my v205    15      0          18   
2       Not as user friendly as the Motorola V300-    11      0           9   
3                   The best phone I've ever owned     4      0           4   
4   I love the phone but it has some real problems    12      0          30   

   no_of_words  no_of_unique_words  rank_no             sub_cat_1  \
0           40                  31  3059436   Carrier Cell Phones   
1          184                 134  3059436   Carrier Cell Phones   
2          121                  90  3059436   Carrier Cell Phones   
3           27                  26  3059436   Carrier Cell Phones   
4          222                 160  3059436   Carrier Cell Phones   

   sub_cat_rank   WC  Analytic  Authentic   Tone    WPS  BigWords    Dic  \
0          4085   64     52.84       3.08  20.23  12.80     17.19  82.81   
1          4085  410     19.19      17.29  58.42  17.08     14.88  90.73   
2          4085  299     52.55      26.84  16.42  33.22     12.71  90.64   
3          4085   55     29.57      74.91  98.85  13.75     18.18  87.27   
4          4085  494     49.88      59.41  41.09  15.94     11.94  89.88   

   Cognition  Affect  tone_pos  tone_neg  emotion  emo_pos  emo_neg  time  \
0       3.13   10.94      4.69      4.69     3.13     0.00     1.56  0.00   
1      13.66    4.39      3.41      0.98     0.98     0.49     0.49  4.39   
2      13.71    5.02      2.34      2.68     2.68     1.00     1.67  2.01   
3      12.73    7.27      7.27      0.00     0.00     0.00     0.00  1.82   
4      13.56    3.04      2.23      0.81     1.62     0.81     0.81  5.26   

   focuspast  focuspresent  focusfuture  Conversation  dominant_topic  \
0       0.00         10.94         0.00          0.00               6   
1       2.20          9.02         2.20          0.73               6   
2       3.01          8.70         0.00          0.00               6   
3       1.82          7.27         3.64          0.00               0   
4       3.85          6.07         0.81          0.00               6   

   total_imp_topics                  custom_topic_name  votes  \
0                 2                            Quality      2   
1                 5                            Quality     15   
2                 2                            Quality     11   
3                 5  Phone related generalized words 1      4   
4                 4                            Quality     12   

   total_imp_topics_0.05  total_imp_topics_0.10  total_imp_topics_0.20  \
0                      2                      2                      1   
1                      5                      3                      1   
2                      2                      2                      2   
3                      5                      4                      2   
4                      4                      3                      2   

   Neutral_Rating  no_of_ent

In [ ]:
i = 32586  # 0, 4, 711, 9212, 9214, 32586
review = df['reviewText'][i]
review 

'great product'

In [ ]:
readability.getmeasures(review, lang = 'en')['readability grades']['FleschReadingEase']

77.90500000000002

In [ ]:
no_of_syllables = syllables.estimate(review)
no_of_syllables

3

In [ ]:
words = len(review.split())
words

2

In [ ]:
sentences = len(sent_tokenize(review))
sentences

1

In [ ]:
readability.FleschReadingEase(no_of_syllables, words, sentences)

77.90500000000002

In [ ]:
206.835 - 1.015 * (words/sentences) - 84.6 * (no_of_syllables/words)

77.90500000000002

In [ ]:
textstat.flesch_reading_ease(review)

77.91

## Flesch Reading Ease Score

In [ ]:
pd.set_option('max_rows', None)

In [ ]:
df.columns

Index(['Rating', 'verified', 'reviewTime', 'Year', 'reviewerID', 'asin',
       'style', 'reviewerName', 'reviewText', 'summary', 'vote', 'Image',
       'no_of_sent', 'no_of_words', 'no_of_unique_words', 'rank_no',
       'sub_cat_1', 'sub_cat_rank', 'WC', 'Analytic', 'Authentic', 'Tone',
       'WPS', 'BigWords', 'Dic', 'Cognition', 'Affect', 'tone_pos', 'tone_neg',
       'emotion', 'emo_pos', 'emo_neg', 'time', 'focuspast', 'focuspresent',
       'focusfuture', 'Conversation', 'dominant_topic', 'total_imp_topics',
       'custom_topic_name', 'votes', 'total_imp_topics_0.05',
       'total_imp_topics_0.10', 'total_imp_topics_0.20', 'Neutral_Rating',
       'no_of_entities'],
      dtype='object')

In [ ]:
df[df['no_of_words'] == 0]   # the emojis in here seem to be creating problems, returning error "I can't do this, there's no words there!"

Rating  verified   reviewTime  Year      reviewerID        asin  \
1154        5      True  07 21, 2016  2016  A35UMIS1JW8W6Y  B001F7VN6M   
1318        5      True   07 6, 2013  2013  A37A8UBNFNIY4Z  B001MRZY3S   
1704        3      True   02 6, 2013  2013  A166ROOM8GI6S2  B0025VKPUW   
2180        5      True  12 29, 2014  2014   A5YNFAM3J9X2V  B0034THXTK   
2862        2      True   10 6, 2016  2016  A2N8IABJ2W2U60  B003X26V50   
3033        3      True  01 25, 2018  2018  A1NPNT3N0BB6S9  B003YHOXFY   
3970        2      True   04 4, 2015  2015   A5QGDA9T88TK3  B004D79DTU   
4028        5      True  12 29, 2014  2014   A5YNFAM3J9X2V  B004DPZ2T2   
5038        5      True  07 16, 2014  2014   ARCJL6N55MNF1  B004WKBW60   
5796        3      True   12 9, 2015  2015  A1551XMICLAQZJ  B0052TQ4FY   
6316        3      True   03 6, 2015  2015  A2G0NTDH8Y3R89  B00598BY6W   
6797        4      True  04 23, 2015  2015  A20N8IQSO87DM6  B005HYU1YE   
7264        5     False  07 16, 2014  2014   ARCJL6N55MNF1  B005MERUHA   
7305        5      True  09 16, 2015  2015  A1SLDOX4392CT4  B005MUC9DY   
7410        1      True   10 7, 2014  2014   AX7UGBDAWDNB3  B005P1O1UO   
7452        5      True  02 10, 2016  2016   AM5HLKCPGL936  B005SHQHSE   
7675        5      True   02 6, 2013  2013  A166ROOM8GI6S2  B005TMMAHU   
9115        5      True   08 2, 2016  2016   AYU6P2IJ2ASLA  B006OU39QW   
9256        5      True  10 10, 2015  2015  A3F9ZTH7D7EEUA  B006QO8QUA   
9329        5      True  02 10, 2016  2016   AM5HLKCPGL936  B006ULGWPK   
9391        5      True  02 10, 2016  2016   AM5HLKCPGL936  B006V70CZ4   
9982        1      True  11 10, 2016  2016  A2N8IABJ2W2U60  B0078ZZ6RM   
10279       1      True  05 29, 2015  2015  A1USV12AIQM12I  B007INF67O   
11242       5      True  02 10, 2016  2016   AM5HLKCPGL936  B008GVG9EQ   
12043       5      True  12 29, 2014  2014   A5YNFAM3J9X2V  B00915VL58   
12241       5      True  10 24, 2014  2014  A3Q509IYH1HQVS  B0092GJNII   
13956       5      True  11 10, 2016  2016  A2N8IABJ2W2U60  B00A29WCA0   
14056       5      True   05 8, 2015  2015  A1Q7VK2FWVKTJ5  B00A29WCA0   
14209       5      True  12 29, 2014  2014   A5YNFAM3J9X2V  B00A29WCA0   
14362       5      True  08 23, 2014  2014   A3B2NEO2H3DCT  B00A29WCA0   
14425       5      True  07 22, 2014  2014   AHKMLSQE8GNMV  B00A29WCA0   
15008       5      True  04 17, 2013  2013   AAW91SZJHFB79  B00ACYW6ZQ   
15058       5      True   01 8, 2015  2015  A2P4PT03EKED8Z  B00AEK5V5K   
15095       5      True   08 6, 2014  2014  A3HND4QWLXS0MG  B00AEK5V5K   
15203       1      True   12 9, 2017  2017  A2VB83Q5U5R4SV  B00AL628HQ   
15720       3      True   11 1, 2014  2014  A1MXF07B833H8A  B00B4HLLB0   
15918       5      True   07 8, 2014  2014   AAW91SZJHFB79  B00B90KCNU   
16106       5      True  10 19, 2015  2015  A3N9CPBQTUHWXP  B00BC0WNUC   
16214       5      True   07 8, 2014  2014   AAW91SZJHFB79  B00BC0WNUC   
16436       5      True   05 6, 2015  2015   AAW91SZJHFB79  B00BI9AKJI   
17016       5      True  10 13, 2015  2015  A2B42XZI4MXOLX  B00BT7E4VO   
17868       5      True  04 16, 2018  2018  A2G72QJ9UXOYP4  B00CBSX5U6   
20017       3     False   11 1, 2014  2014   ANHMR1BB49UIG  B00D8T9QZU   
20134       5      True  02 28, 2016  2016  A193G3N6SFJQD3  B00D99ZBR6   
20582       5      True   07 8, 2014  2014   AAW91SZJHFB79  B00DGJ6E34   
20684       1      True  05 21, 2015  2015  A338DK1FG8CDTO  B00DKEX5AU   
21105       5      True  03 12, 2015  2015   AYR4JS918FOPX  B00DRNEV9S   
21229       4     False   11 1, 2014  2014   ANHMR1BB49UIG  B00DRNEV9S   
21366       5     False   07 8, 2014  2014   AAW91SZJHFB79  B00DRNEV9S   
21667       5      True   05 6, 2015  2015   AAW91SZJHFB79  B00DZS9050   
22366       5      True   05 8, 2015  2015  A1Q7VK2FWVKTJ5  B00EAYWESI   
22961       5      True   05 8, 2015  2015  A1Q7VK2FWVKTJ5  B00EZHM9JE   
23064       2      True  04 25, 2016  2016  A3T53WG8X4GX2P  B00F2COJSK   
24189      

In [ ]:
emojis_index = [1318, 7305, 12241, 14425, 15720, 17016, 20017, 21229, 24189, 37377, 43236]

In [ ]:
df.drop(emojis_index, inplace = True)

In [ ]:
df.reset_index(inplace=True)

In [ ]:
rows = list(df.index)

In [ ]:
reading_score = [readability.getmeasures(df['reviewText'][i], lang = 'en')['readability grades']['FleschReadingEase'] for i in rows]

In [ ]:
print(reading_score)

[20.262500000000017, 65.63107547169813, 77.2805568934377, 38.20214285714288, -58.78570399476094, 43.23944963655247, 80.04908174097666, 62.175882352941194, 68.00321923937362, 8.69524433427766, 88.89458178438663, 64.38000000000002, 29.908371735791107, -12.594999999999985, -6.173388429752038, 43.485495495495506, -71.565243902439, 54.50423267326735, -9.414854368932012, -158.87132075471692, 35.791775510204104, 8.647241379310358, -19.65846153846151, 35.822881355932225, 137.815, 37.00027586206898, -24.439534883720896, 37.108908227848126, 75.50000000000001, 58.45209152752011, 35.42596774193551, 64.1126829268293, 75.18237984496125, 61.42955710955712, 76.21978200952145, 0.9609582689335525, -116.34350230414742, 28.72880952380956, -10.899241917502763, 83.16048576732675, 84.49875000000003, 80.62695595854925, 62.93220375722545, 24.59642857142859, 61.16432327761927, 43.13654868784531, 64.51826923076925, 66.86220279720283, 74.75736301369864, -38.72394736842101, 51.87005597014927, 32.23813559322036, 83

In [ ]:
reading_score_textstat = [textstat.flesch_reading_ease(df['reviewText'][i]) for i in rows]

In [ ]:
print(reading_score_textstat)

[75.4, 79.6, 63.77, 74.39, 88.26, 78.38, 81.43, 88.36, 55.27, 69.62, 83.25, 81.26, 71.44, 76.22, 92.42, 79.7, 64.95, 77.77, 75.81, 71.04, 72.05, 76.32, 67.49, 60.65, 79.27, 74.29, 82.34, 75.3, 104.64, 75.0, 76.01, 82.95, 64.34, 91.0, 69.62, 65.25, 82.24, 70.63, 64.41, 79.26, 75.5, 80.92, 79.7, 67.89, 82.85, 75.84, 87.42, 76.66, 81.02, 77.77, 70.53, 65.22, 93.24, 73.47, 82.24, 79.7, 74.19, 73.71, 75.44, 77.37, 72.8, 64.95, 77.67, 67.28, 76.01, 83.86, 73.17, 99.06, 93.14, 111.58, 81.93, 71.75, 77.47, 68.1, 79.9, 60.89, 66.37, 82.34, 120.21, 76.22, 88.16, 64.95, 79.6, 51.55, 84.07, 71.65, 84.88, 76.05, 89.75, 90.77, 119.19, -47.99, 96.18, -47.99, 77.91, 119.19, -6.7, 119.19, 32.56, 120.21, 56.25, 109.21, 120.21, 121.22, 121.22, -47.99, 36.62, 83.15, -47.99, 88.74, 86.2, -47.99, 103.63, 63.36, 71.51, 97.4, 106.47, 75.54, 77.23, 94.66, 76.72, 90.29, 87.55, 59.98, 56.59, 103.97, 91.11, 78.99, 66.07, 52.7, 88.57, 83.15, 66.44, 82.34, 78.59, 81.83, 68.4, 72.05, 75.1, 78.96, 82.44, 74.08, 90.6,

In [ ]:
reading_score_own = [readability.FleschReadingEase(syllables.estimate(df['reviewText'][i]), len(df['reviewText'][i].split()), len(sent_tokenize(df['reviewText'][i]))) for i in rows]

In [ ]:
print(reading_score_own)

[60.33362500000003, 68.97243344199948, 51.36653773227154, 63.67147727272727, 75.55957923497269, 66.03785041113221, 71.14146198830412, 81.63033333333334, 45.283826530612274, 62.57355440759875, 85.39156716417912, 89.9019648203593, 64.88818381180225, 72.88966666666668, 91.11067398119124, 68.57140500950466, 49.133888888888904, 65.97975000000002, 58.325575495049506, 70.9388300907912, 55.84472246891653, 65.35180722891567, 65.76586086637299, 54.71315789473687, 171.0808823529412, 56.09039473684213, 76.8634108527132, 62.21108305983341, 75.50000000000001, 67.81590909090912, 66.85855737704921, 75.3486991869919, 46.02108614232212, 76.33333333333334, 64.30141891891893, 55.77829225352114, 71.32500000000002, 61.49187500000001, 54.09882755842063, 68.57034090909093, 55.848829588015015, 61.63785087719298, 74.8616469428008, 59.79763833746901, 74.57046825723299, 64.43642026578075, 78.97000000000003, 71.31254269449718, 72.85717527386544, 80.64375000000003, 66.78523711340208, 63.75887931034484, 84.866843198

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity([reading_score], [reading_score_textstat])

array([[0.75438691]])

In [ ]:
cosine_similarity([reading_score], [reading_score_own])

array([[0.82526096]])

In [ ]:
cosine_similarity([reading_score_own], [reading_score_textstat])

array([[0.90990361]])

In [ ]:
df['reading_score'] = reading_score
df['reading_score_textstat'] = reading_score_textstat
df['reading_score_own'] = reading_score_own